### ISSUE TITLE
Instructions to run the project missing

### ISSUE THREAD

**Issue by staeff** [janlemcke/fahrraddiebstahl_berlin#1]
Hi, I am interested in your project and wanted to run in locally, but it failed like this:

```sh
/settings.py", line 19, in <module>
    with open('./config.json') as key_file:
FileNotFoundError: [Errno 2] No such file or directory: './config.json'
```
Could you provide the information, what needs to be in `./config.json`? Maybe adding a `config.json.example` file to the project?

**Comment by janlemcke** [comment]
Hey,

you need to check the passages within the code where this config file is used. This file contains private keys and passwords, that’s why you need to locally create it. In my config file are the api keys for the twitter bot. I think you do not want to build exactly the same bot, so that is not necessary. The only thing left is then the secret key for within your Django settings. If you create a new Django project, you will get one included in this new project. Just copy this key and paste it in the gir project.

***@***.***

Kind regards,
Jan

Von: Stephan Klinger ***@***.***>
Datum: Donnerstag, 17. Februar 2022 um 18:44
An: janlemcke/fahrraddiebstahl_berlin ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [janlemcke/fahrraddiebstahl_berlin] Instructions to run the project missing (Issue #1)

Hi, I am interested in your project and wanted to run in locally, but it failed like this:

/settings.py", line 19, in <module>

    with open('./config.json') as key_file:

FileNotFoundError: [Errno 2] No such file or directory: './config.json'

Could you provide the information, what needs to be in ./config.json? Maybe adding a config.json.example file to the project?

**Comment by staeff** [comment]
Hi, thanks for the reply. That helped. I mostly want to check it out for the data part and dashboard not the Twitter connection. Closing this issue, because its solved. Are you actively developing the project? For me the https://fahrraddiebstahl-berlin.de/ site does not load the map. Locally it works. I will probably poke around a bit and see, if I am getting the same when deploying.

**Comment by janlemcke** [comment]
Hey Stephan,

i would love to further develop the project. But currently I’m just too busy (writing exams for my Masters degree). I need to fix something on the server that’s why it is not working. In Addition, I wanted to add additional charts like pairplots etc. to maybe discover some correlations between the features etc. If you are interested in this stuff, you could program something and create a pull request.

Kind regards,
Jan

Von: Stephan Klinger ***@***.***>
Datum: Freitag, 18. Februar 2022 um 16:47
An: janlemcke/fahrraddiebstahl_berlin ***@***.***>
Cc: Jan ***@***.***>, Comment ***@***.***>
Betreff: Re: [janlemcke/fahrraddiebstahl_berlin] Instructions to run the project missing (Issue #1)

Hi, thanks for the reply. That helped. I mostly want to check it out for the data part and dashboard not the Twitter connection. Closing this issue, because its solved. Are you actively developing the project? For me the https://fahrraddiebstahl-berlin.de/<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Ffahrraddiebstahl-berlin.de%2F&data=04%7C01%7C%7Caba571e840814515e08708d9f2f5e99b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637807960261247849%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=YF0Vgza0oORH1ILBbBzIwcTbQ3Rn2uobUQ1UKg1yNrg%3D&reserved=0> site does not load the map. Locally it works. I will probably poke around a bit and see, if I am getting the same when deploying.
